# bash script debugging
[ -f $HOME/.bashdebug ] && source $HOME/.bashdebug

# configure bash
[ -f $HOME/.bashrc_config ] && source $HOME/.bashrc_config

# customize bash environment, aliases, and functions
if [[ -z $HAVE_MJB_BASH_ENV ]]; then

    debugecho .bashrc sourcing .bashrc_env_pre
    [ -f $HOME/.bashrc_env_pre ] && source $HOME/.bashrc_env_pre
    debugecho .bashrc sourcing .bashrc_aliases
    [ -f $HOME/.bashrc_aliases ] && source $HOME/.bashrc_aliases
    debugecho .bashrc sourcing .bashrc_functions
    [ -f $HOME/.bashrc_functions ] && source $HOME/.bashrc_functions
    debugecho .bashrc sourcing .bashrc_env_post
    [ -f $HOME/.bashrc_env_post ] && source $HOME/.bashrc_env_post

    export HAVE_MJB_BASH_ENV=yes

    # set custom prompt
    if [[ -n $PS1 ]]; then
        #debugecho .bashrc setting custom prompt
        phost=$(hostname -s)
        export PS1="\[\e[31;47m\]$phost \[\e[1m\]\w\[\e[0m\]\n(\#) \[\e[1m\]>\[\e[0m\] "
    fi
fi

#### EVERY TIME SETTINGS ####

# gpg-agent support
if [[ -n $PS1 ]]; then
   export GPG_TTY=$(tty)
fi
