export HAVE_MJB_BASH_CONFIG=yes

. ${HOME}/.bashdebug

if [ "x$MJB_ENV_SET" != "xyes" ]; then

    # bash setup
    debugecho .bashrc sourcing .bashrc_env_pre
    [ -f $HOME/.bashrc_env_pre ] && source $HOME/.bashrc_env_pre
    debugecho .bashrc sourcing .bashrc_aliases
    [ -f $HOME/.bashrc_aliases ] && source $HOME/.bashrc_aliases
    debugecho .bashrc sourcing .bashrc_functions
    [ -f $HOME/.bashrc_functions ] && source $HOME/.bashrc_functions
    debugecho .bashrc sourcing .bashrc_env_post
    [ -f $HOME/.bashrc_env_post ] && source $HOME/.bashrc_env_post

    # custom prompt
    if [ "$PS1" ]; then
        #debugecho .bashrc setting custom prompt
        phost=$(hostname -s)
        export PS1="\[\e[31;47m\]$phost \[\e[1m\]\w\[\e[0m\]\n(\#) \[\e[1m\]>\[\e[0m\] "
    fi

    export MJB_ENV_SET=yes
fi
